### ISSUE TITLE
"Some index files failed to download. They have been ignored, or old ones used instead"

### ISSUE THREAD

**Issue by AStroEngineerSOC** [yandex-cloud-examples/yc-courses-ru-devsecops#2]
Сборка образа по команде "docker compose build" завершается ошибкой на 3 шаге:
"RUN apt-get update && apt-get install -y locales ca-certificates --no-install-recommends \
    && printf 'en_US.UTF-8 UTF-8\n' >> /etc/locale.gen && locale-gen \
    && rm -rf /var/cache/apt/archives/*"

Не может достучаться до http://deb.debian.org/debian stretch InRelease
"#0 0.529 Ign:1 http://deb.debian.org/debian stretch InRelease"

Возможно стоит использовать более свежую версию образа python

**Comment by maxvoyakin** [comment]
the same

**Comment by svitru** [comment]
diff --git a/Dockerfile b/Dockerfile

```
-RUN apt-get update && apt-get install -y locales ca-certificates --no-install-recommends \
+RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list && apt-get update && apt-get install -y locales ca-certificates --no-install-recommends \
     && printf 'en_US.UTF-8 UTF-8\n' >> /etc/locale.gen && locale-gen \
     && rm -rf /var/cache/apt/archives/*
```

**Comment by narek01** [comment]
Try to replace base image in Dockerfile by a newer one. For instance, `python:3.9.16-slim` worked for me.

**Comment by kazhem-ht** [comment]
Там намеренно используется старый образ python на основе debian stretch со множеством уязвимостей. Обновили, как было предложено, sources list на архивный в Dockerfile
